wl_play gets you right into a game

diff --git a/cli/_wl_base b/cli/_wl_base
--- a/cli/_wl_base
+++ b/cli/_wl_base
@@ -19,9 +19,14 @@ function die {
 }
 
 function error {
+  NO_NEWLINE=""
+  if [[ ${1} == "-n" ]] ; then
+    NO_NEWLINE="-n"
+    shift
+  fi
   RED='\033[38;5;9m'
   NC='\033[0m' # No Color
-  echo 1>&2 -e -n "\n${RED}${@}${NC}"
+  echo 1>&2 -e ${NO_NEWLINE} "\n${RED}${@}${NC}"
 }
 
 function error_stdout {
@@ -59,6 +64,12 @@ function session_email {
   session_val email
 }
 
+function current_room {
+  if [[ -f ${CURRENT_ROOM} ]] ; then
+    cat ${CURRENT_ROOM}
+  fi
+}
+
 function lang {
   echo "${LANG}" | awk -F '_' '{print $1}'| tr '[:upper:]' '[:lower:]'
 }
@@ -77,7 +88,7 @@ function translate_message {
       echo "please join a room first. view rooms with wl_rooms, join with wl_join"
     ;;
     'err.room.notFound')
-      echo "room not found, try signing off and signing back on"
+      echo "room not found"
     ;;
     'err.game.notYourTurn')
       echo "it's not your turn"
@@ -85,8 +96,11 @@ function translate_message {
     'err.game.invalidPlay')
       echo "word cannot be played"
     ;;
-    'err.api.boardPreview')
-      echo "error previewing board"
+    'err.game.noCurrentPlay')
+      echo "no current word to play"
+    ;;
+    'err.api.boardView')
+      echo "error viewing board"
     ;;
     'err.api.unavailable')
       echo "wordland server unavailable"
@@ -97,6 +111,27 @@ function translate_message {
     'err.api.login')
       echo "error signing on"
     ;;
+    'err.api.registration')
+      echo "error signing up"
+    ;;
+    'msg.signup.success')
+      echo "Successfully signed up and logged in as"
+    ;;
+    'msg.signin.success')
+      echo "Successfully signed in as"
+    ;;
+    'msg.signoff.success')
+      echo "Successfully signed off as"
+    ;;
+    'msg.user.anonymousFlag')
+      echo "(anonymous)"
+    ;;
+    'err.notLoggedIn')
+      echo "not logged in"
+    ;;
+    'err.api.join')
+      echo "error joining room"
+    ;;
     'err.api.noSessionId')
       echo "session ID is missing, try signing off and signing back on"
     ;;
@@ -105,6 +140,9 @@ function translate_message {
     ;;
     'err.email.required')
       echo "email is required"
+    ;;
+    'err.room.required')
+      echo "room name is required"
     ;;
     'err.word.invalid')
       echo "not a word"
@@ -120,6 +158,35 @@ function translate_message {
     ;;
     'label.password')
       echo "Password"
+    ;;
+    'label.optional')
+      echo "(optional)"
+    ;;
+    'msg.availableRooms')
+      echo "Available rooms:"
+    ;;
+    'msg.roomDetails')
+      echo "Details for room: "
+    ;;
+    'label.board.name')
+      echo "Board name:       "
+    ;;
+    'label.board.dimensions')
+      echo "Board dimensions: "
+    ;;
+    'label.maxPlayers')
+      echo "Max players:      "
+    ;;
+    'msg.chooseRoom')
+      echo "Enter a room name or number to see more info, or Control-C to exit"
+    ;;
+    'msg.roomOptions')
+      echo "Commands: "
+      echo "  n   - start a new game in this room"
+      echo "  r   - back to rooms list"
+      echo "  v   - show verbose room definition (JSON)"
+      echo "  q   - quit (or Control-C)"
+      echo ; echo ""
     ;;
     'Y')
       echo "Y"
@@ -137,6 +204,37 @@ function translate_messages {
   for err in ${@} ; do
     translate_message "${err}"
   done
+}
+
+function wl_prompt {
+  name="$(session_name)"
+  if [[ -z "${name}" ]] ; then
+    name="not-signed-on"
+  fi
+  room="$(current_room)"
+  if [[ ! -z "${WL_VERBOSE_PROMPT}" && "${WL_VERBOSE_PROMPT}" == "Y" ]] ; then
+    if [[ ! -z "${room}" ]] ; then
+      room="/${room}"
+    fi
+    echo "${name}@$(echo "${WL_API}" | awk -F[/:] '{print $4}')${room}>>> "
+  else
+    if [[ ! -z "${room}" ]] ; then
+    room="@${room}"
+    fi
+    echo "${name}${room}>>> "
+  fi
+}
+
+function wl_exists {
+  SESSION_TOKEN="${1}"
+  URL="${2}"
+  response=$(curl --silent --write-out "\n%{http_code}\n" --header "${SESSION_TOKEN}" ${URL})
+  status_code=$(echo "${response}" | sed -n '$p')
+  if [[ -z "${status_code}" || ${status_code} -ne 200 ]] ; then
+    echo "false"
+  else
+    echo "true"
+  fi
 }
 
 function wl_get {
diff --git a/cli/wl_play b/cli/wl_play
--- a/cli/wl_play
+++ b/cli/wl_play
@@ -7,12 +7,18 @@ SCRIPT_DIR=$(cd $(dirname ${SCRIPT}) && pwd)
 ROOM_NAME="${1}"
 if [[ -z "${ROOM_NAME}" ]] ; then
   if [[ ! -f "${CURRENT_ROOM}" ]] ; then
-    die "$(translate_message err.room.noCurrentRoom)"
+    error "$(translate_message err.room.noCurrentRoom)"
+    exec ${SCRIPT_DIR}/wl_rooms
   fi
-  ROOM_NAME="$(cat ${CURRENT_ROOM})"
+  ROOM_NAME="$(current_room)"
+  if [[ -z "${ROOM_NAME}" ]] ; then
+    error "$(translate_message err.room.noCurrentRoom)"
+    exec ${SCRIPT_DIR}/wl_rooms
+  fi
 fi
 if [[ ! -f "${WL_DIR}/rooms/${ROOM_NAME}/room.json" ]] ; then
-  die "$(translate_message err.room.notFound)"
+    error "$(translate_message err.room.noCurrentRoom)"
+    exec ${SCRIPT_DIR}/wl_rooms
 fi
 
 TILES_JSON_PREFIX="{ \"tiles\": [ "
@@ -92,19 +98,12 @@ function board_preview_obj {
   echo -n "${TILES_JSON_SUFFIX}"
 }
 
-function wl_prompt {
-  name="$(session_name)"
-  if [[ -z "${name}" ]] ; then
-    name="not-signed-on"
-  fi
-  echo "${name}@$(echo "${WL_API}" | awk -F[/:] '{print $4}')>>> "
-}
+X1=$(cat ${WL_DIR}/rooms/${ROOM_NAME}/x1)
+Y1=$(cat ${WL_DIR}/rooms/${ROOM_NAME}/y1)
+VIEW_SIZE=$(cat ${WL_DIR}/rooms/${ROOM_NAME}/view_size)
 
-X1=${1:-$(cat ${WL_DIR}/rooms/${ROOM_NAME}/x1)}
-Y1=${2:-$(cat ${WL_DIR}/rooms/${ROOM_NAME}/x1)}
-VIEW_SIZE=${3:-$(cat ${WL_DIR}/rooms/${ROOM_NAME}/view_size)}
 board="$(echo "{}" | wl_post "${SESSION_TOKEN}" "${WL_API}/rooms/${ROOM_NAME}/board/preview.txt?x1=${X1}&x2=$(expr ${X1} + ${VIEW_SIZE})&y1=${Y1}&y2=$(expr ${Y1} + ${VIEW_SIZE})")" \
-  || die "$(translate_message err.api.boardPreview)"
+  || die "$(translate_message err.api.boardView)"
 
 printf "$(printf "$(json_node "${board}" grid | tr -d '"')")"
 echo ; echo ; echo -n "$(wl_prompt)"
@@ -151,7 +150,7 @@ while IFS= read -s -r -n1 char ; do
     ;;
     '')
       if [[ -z "${CURRENT_PLAY}" ]] ; then
-        error "no current play"
+        error "$(translate_message err.game.noCurrentPlay)"
       else
         play_output="$(wl_post "${SESSION_TOKEN}" "${WL_API}/rooms/${ROOM_NAME}/play" "$(play_obj)" || die "error playing word")"
         reset_play
@@ -178,7 +177,7 @@ while IFS= read -s -r -n1 char ; do
     POST_ENTITY="$(board_preview_obj)"
   fi
   board="$(wl_post "${SESSION_TOKEN}" "${WL_API}/rooms/${ROOM_NAME}/board/preview.txt?x1=${X1}&x2=$(expr ${X1} + ${VIEW_SIZE})&y1=${Y1}&y2=$(expr ${Y1} + ${VIEW_SIZE})" "${POST_ENTITY}")" \
-    || die "error previewing board"
+    || die "$(translate_message err.api.boardView)"
 
   echo
   printf "$(printf "$(json_node "${board}" grid | tr -d '"')")"
@@ -191,7 +190,7 @@ while IFS= read -s -r -n1 char ; do
   if [[ ${#TILES[*]} -gt 0 ]] ; then
     SUCCESS="$(json_val "${board}" success)"
     if [[ -z "${SUCCESS}" || "${SUCCESS}" != "true" ]] ; then
-      error "$(translate_message 'err.game.invalidPlay')"
+      error -n "$(translate_message 'err.game.invalidPlay')"
       CURRENT_PLAY=""
     else
       CURRENT_PLAY="$(json_node "${board}" playedTiles)"
