WIP. update CLI to better support joining games, other fixes

diff --git a/cli/wl_join b/cli/wl_join
--- a/cli/wl_join
+++ b/cli/wl_join
@@ -15,15 +15,21 @@ function join_obj () {
 EOF
 }
 
+TEMP_SESSION=$(mktemp /tmp/wl_room_session.XXXXXXXX.json)
+wl_post "${SESSION_TOKEN}" ${WL_API}/rooms/${ROOM_NAME}/join "$(join_obj)" ${TEMP_SESSION} || die "error joining game"
+if [[ ! -f ${TEMP_SESSION} || ! -s ${TEMP_SESSION} ]] ; then
+  die "error joining game"
+fi
+ROOM_NAME="$(cat ${TEMP_SESSION} | grep -m 1 '"room"' | awk -F '"' '{print $4}')"
 ROOM_DIR="${WL_DIR}/rooms/${ROOM_NAME}"
 mkdir -p ${ROOM_DIR}
-curl --header "Content-Type: application/json" -X POST -d "$(join_obj)" ${WL_API}/rooms/${ROOM_NAME}/join > ${ROOM_DIR}/session.json \
-  || die "error joining game"
 
 echo "${ROOM_NAME}" > ${WL_DIR}/current_room
 echo "0" > ${ROOM_DIR}/x1
 echo "0" > ${ROOM_DIR}/y1
 echo "10" > ${ROOM_DIR}/view_size
+
+exit 0
 
 # show board
 ${SCRIPT_DIR}/board
