WIP. working on async play

diff --git a/cli/wl_play b/cli/wl_play
--- a/cli/wl_play
+++ b/cli/wl_play
@@ -6,10 +6,6 @@ SCRIPT_DIR=$(cd $(dirname ${SCRIPT}) && pwd)
 
 ROOM_NAME="${1}"
 if [[ -z "${ROOM_NAME}" ]] ; then
-  if [[ ! -f "${CURRENT_ROOM}" ]] ; then
-    error "$(translate_message err_room_noCurrentRoom)"
-    exec ${SCRIPT_DIR}/wl_rooms
-  fi
   ROOM_NAME="$(current_room)"
   if [[ -z "${ROOM_NAME}" ]] ; then
     error "$(translate_message err_room_noCurrentRoom)"
@@ -20,6 +16,39 @@ if [[ ! -f "${WL_DIR}/rooms/${ROOM_NAME}/room.json" ]] ; then
     error "$(translate_message err_room_noCurrentRoom)"
     exec ${SCRIPT_DIR}/wl_rooms
 fi
+
+NO_JOIN="${2}"
+if [[ -z ${NO_JOIN} || "${NO_JOIN}" != "-n" ]] ; then
+  exec ${SCRIPT_DIR}/wl_join ${ROOM_NAME}
+fi
+
+WL_PLAY_PID="$$"
+WEBSOCKET_PID="${3}"
+if [[ -z ${WEBSOCKET_PID} ]] ; then
+  set -e
+  ${SCRIPT_DIR}/_wl_websocket ${WL_PLAY_PID} < /dev/null &
+  WEBSOCKET_PID=$!
+  disown %1
+  echo "Restarting without websocket"
+  exec ${0} ${ROOM_NAME} -n ${WEBSOCKET_PID}
+else
+  echo "wl_play running without starting websocket, it is running on ${WEBSOCKET_PID}"
+fi
+
+function shutdown_wl_play {
+  echo "checking if websocket is running"
+  if [[ $(ps uxw | grep ${WEBSOCKET_PID} | grep -v grep | wc -l | tr -d ' ') -gt 0 ]] ; then
+    echo "it is: $(ps uxw | grep ${WEBSOCKET_PID} | grep -v grep)"
+    kill -TERM ${WEBSOCKET_PID} || error "$(translate_message err_websocket_shutdown)"
+    kill -9 ${WEBSOCKET_PID} 2> /dev/null
+  fi
+  echo "kill -9 to wl_play ${WL_PLAY_PID}"
+  kill -9 ${WL_PLAY_PID}
+  exit 1
+}
+
+trap 'shutdown_wl_play' INT TERM EXIT
+trap 'async_fresh_board_view' USR1
 
 ACTIVE_CHAR=""
 ACTIVE_CHAR_INDEX=1
@@ -95,15 +124,15 @@ BOARD_REQUEST_JSON_SUFFIX=" ] }"
 
 function board_preview_obj {
   echo -n "${BOARD_REQUEST_PREFIX}"
-  if [[ -f ${ROOM_PALETTE} ]] ; then
-    echo -n "$(cat ${ROOM_PALETTE})"
+  if [[ -f ${ROOM_PALETTE} && $(cat ${ROOM_PALETTE} | tr -d ' \n' | wc -c | tr -d ' ') -gt 0 ]] ; then
+    cat ${ROOM_PALETTE}
   else
     echo -n "null"
   fi
   echo -n "${BOARD_REQUEST_TILES_JSON_PREFIX}"
   first=1
   for tile in "${TILES[@]}" ; do
-    if [ $first -ne 1 ] ; then
+    if [ ${first} -ne 1 ] ; then
       echo -n "${BOARD_REQUEST_TILES_JSON_SEP}"
     fi
     if [[ "${tile}" =~ /null/ ]] ; then
@@ -115,14 +144,60 @@ function board_preview_obj {
   echo -n "${BOARD_REQUEST_JSON_SUFFIX}"
 }
 
-board_status="$(wl_post "${SESSION_TOKEN}" "${WL_API}/rooms/${ROOM_NAME}/board/preview.txt?x1=${X1}&x2=$(expr ${X1} + ${VIEW_SIZE})&y1=${Y1}&y2=$(expr ${Y1} + ${VIEW_SIZE})" "{}" "${BOARD_JSON}")" \
-  || die "$(translate_message err_api_boardView)"
+function save_palette {
+  PALETTE="$(json_node "$(cat ${BOARD_JSON})" palette)"
+  if [[ ! -z "${PALETTE}" ]] ; then
+    echo "${PALETTE}" > ${ROOM_PALETTE}
+  fi
+}
 
-# save palette
-echo "$(json_node "$(cat ${BOARD_JSON})" palette)" > ${ROOM_PALETTE}
+function show_tray {
+  if [[ ${#TILES[*]} -gt 0 ]] ; then
+    SUCCESS="$(json_val "$(cat ${BOARD_JSON})" success)"
+    if [[ -z "${SUCCESS}" || "${SUCCESS}" != "true" ]] ; then
+      error -n "$(translate_message 'err_game_invalidPlay')"
+      CURRENT_PLAY=""
+    else
+      CURRENT_PLAY="$(json_node "$(cat ${BOARD_JSON})" playedTiles)"
+    fi
+  fi
+  echo
+  if [[ -z "$(current_word)" ]] ; then
+    echo "   [  (empty)  ]"
+    echo
+  else
+    echo "   [  $(current_word)  ]"
+    echo -n "     "
+    i=0
+    while [[ ${i} -lt $(echo -n "$(current_word)" | wc -c | tr -d ' ') ]] ; do
+      echo -n " "
+      i=$(expr ${i} + 1)
+    done
+    echo "^"
+  fi
+}
 
-printf "$(printf "$(json_node "$(cat ${BOARD_JSON})" grid | tr -d '"')")"
-echo ; echo ; echo "   [  (empty)  ]" ; echo ; echo -n "$(wl_prompt)"
+function show_board {
+  board_status="$(wl_post "${SESSION_TOKEN}" "${WL_API}/rooms/${ROOM_NAME}/board/preview.txt?x1=${X1}&x2=$(expr ${X1} + ${VIEW_SIZE})&y1=${Y1}&y2=$(expr ${Y1} + ${VIEW_SIZE})" "$(board_preview_obj)" "${BOARD_JSON}")" \
+    || die "$(translate_message err_api_boardView)"
+
+  save_palette
+
+  # Show the board preview
+  echo
+  printf "$(printf "$(json_node "$(cat ${BOARD_JSON})" grid | tr -d '"')")"
+}
+
+function fresh_board_view {
+  show_board ; echo ; show_tray
+  echo -n "$(wl_prompt)"
+}
+
+function async_fresh_board_view {
+  echo ; echo ; echo "<?~~~ !! async update !! ~~~~?>"; fresh_board_view
+}
+
+fresh_board_view
 
 while IFS= read -s -r -n1 char ; do
   reset=0
@@ -213,15 +288,7 @@ while IFS= read -s -r -n1 char ; do
   if [[ ${reset} -eq 1 ]] ; then
     reset=0
   fi
-  board_status="$(wl_post "${SESSION_TOKEN}" "${WL_API}/rooms/${ROOM_NAME}/board/preview.txt?x1=${X1}&x2=$(expr ${X1} + ${VIEW_SIZE})&y1=${Y1}&y2=$(expr ${Y1} + ${VIEW_SIZE})" "$(board_preview_obj)" "${BOARD_JSON}")" \
-    || die "$(translate_message err_api_boardView)"
-
-  # save palette
-  echo "$(json_node "$(cat ${BOARD_JSON})" palette)" > ${ROOM_PALETTE}
-
-  # Show the board preview
-  echo
-  printf "$(printf "$(json_node "$(cat ${BOARD_JSON})" grid | tr -d '"')")"
+  show_board
 
   # If the play resulted in a message to the user, show that here
   if [[ ! -z "${play_output}" ]] ; then
@@ -231,29 +298,7 @@ while IFS= read -s -r -n1 char ; do
 
   # Show the tray
   echo
-  if [[ ${#TILES[*]} -gt 0 ]] ; then
-    SUCCESS="$(json_val "$(cat ${BOARD_JSON})" success)"
-    if [[ -z "${SUCCESS}" || "${SUCCESS}" != "true" ]] ; then
-      error -n "$(translate_message 'err_game_invalidPlay')"
-      CURRENT_PLAY=""
-    else
-      CURRENT_PLAY="$(json_node "$(cat ${BOARD_JSON})" playedTiles)"
-    fi
-  fi
-  echo
-  if [[ -z "$(current_word)" ]] ; then
-    echo "   [  (empty)  ]"
-    echo
-  else
-    echo "   [  $(current_word)  ]"
-    echo -n "     "
-    i=0
-    while [[ ${i} -lt $(echo -n "$(current_word)" | wc -c | tr -d ' ') ]] ; do
-      echo -n " "
-      i=$(expr ${i} + 1)
-    done
-    echo "^"
-  fi
+  show_tray
 
   echo -n "$(wl_prompt)"
 
