make translations file more shell-friendly

diff --git a/cli/wl_play b/cli/wl_play
--- a/cli/wl_play
+++ b/cli/wl_play
@@ -7,17 +7,17 @@ SCRIPT_DIR=$(cd $(dirname ${SCRIPT}) && pwd)
 ROOM_NAME="${1}"
 if [[ -z "${ROOM_NAME}" ]] ; then
   if [[ ! -f "${CURRENT_ROOM}" ]] ; then
-    error "$(translate_message err.room.noCurrentRoom)"
+    error "$(translate_message err_room_noCurrentRoom)"
     exec ${SCRIPT_DIR}/wl_rooms
   fi
   ROOM_NAME="$(current_room)"
   if [[ -z "${ROOM_NAME}" ]] ; then
-    error "$(translate_message err.room.noCurrentRoom)"
+    error "$(translate_message err_room_noCurrentRoom)"
     exec ${SCRIPT_DIR}/wl_rooms
   fi
 fi
 if [[ ! -f "${WL_DIR}/rooms/${ROOM_NAME}/room.json" ]] ; then
-    error "$(translate_message err.room.noCurrentRoom)"
+    error "$(translate_message err_room_noCurrentRoom)"
     exec ${SCRIPT_DIR}/wl_rooms
 fi
 
@@ -103,7 +103,7 @@ Y1=$(cat ${WL_DIR}/rooms/${ROOM_NAME}/y1)
 VIEW_SIZE=$(cat ${WL_DIR}/rooms/${ROOM_NAME}/view_size)
 
 board="$(echo "{}" | wl_post "${SESSION_TOKEN}" "${WL_API}/rooms/${ROOM_NAME}/board/preview.txt?x1=${X1}&x2=$(expr ${X1} + ${VIEW_SIZE})&y1=${Y1}&y2=$(expr ${Y1} + ${VIEW_SIZE})")" \
-  || die "$(translate_message err.api.boardView)"
+  || die "$(translate_message err_api_boardView)"
 
 printf "$(printf "$(json_node "${board}" grid | tr -d '"')")"
 echo ; echo ; echo -n "$(wl_prompt)"
@@ -157,9 +157,9 @@ while IFS= read -s -r -n1 char ; do
     # Submit the letters in the tray as our play, if there are any
     '')
       if [[ -z "${CURRENT_PLAY}" ]] ; then
-        error "$(translate_message err.game.noCurrentPlay)"
+        error "$(translate_message err_game_noCurrentPlay)"
       else
-        play_output="$(wl_post "${SESSION_TOKEN}" "${WL_API}/rooms/${ROOM_NAME}/play" "$(play_obj)" || die "$(translate_error err.api.play)")"
+        play_output="$(wl_post "${SESSION_TOKEN}" "${WL_API}/rooms/${ROOM_NAME}/play" "$(play_obj)" || die "$(translate_error err_api_play)")"
         if [[ -z "${play_output}" ]] ; then
           reset_play
           reset=1
@@ -174,7 +174,7 @@ while IFS= read -s -r -n1 char ; do
 
     # Clear the tray
     ' ')
-      echo ; echo "$(translate_message msg.word.reset)"
+      echo ; echo "$(translate_message msg_word_reset)"
       reset_play
       reset=1
     ;;
@@ -198,7 +198,7 @@ while IFS= read -s -r -n1 char ; do
     POST_ENTITY="$(board_preview_obj)"
   fi
   board="$(wl_post "${SESSION_TOKEN}" "${WL_API}/rooms/${ROOM_NAME}/board/preview.txt?x1=${X1}&x2=$(expr ${X1} + ${VIEW_SIZE})&y1=${Y1}&y2=$(expr ${Y1} + ${VIEW_SIZE})" "${POST_ENTITY}")" \
-    || die "$(translate_message err.api.boardView)"
+    || die "$(translate_message err_api_boardView)"
 
   # Show the board preview
   echo
@@ -214,7 +214,7 @@ while IFS= read -s -r -n1 char ; do
   if [[ ${#TILES[*]} -gt 0 ]] ; then
     SUCCESS="$(json_val "${board}" success)"
     if [[ -z "${SUCCESS}" || "${SUCCESS}" != "true" ]] ; then
-      error -n "$(translate_message 'err.game.invalidPlay')"
+      error -n "$(translate_message 'err_game_invalidPlay')"
       CURRENT_PLAY=""
     else
       CURRENT_PLAY="$(json_node "${board}" playedTiles)"
